Fix requirements.txt installation failure
Collecting git+git://github.com/Pycord-Development/pycord@1d65214 (from -r requirements.txt (line 2))

  Cloning git://github.com/Pycord-Development/pycord (to revision 1d65214) to /tmp/pip-req-build-kd9qoj75

  Running command git clone -q git://github.com/Pycord-Development/pycord /tmp/pip-req-build-kd9qoj75

  fatal: remote error:

    The unauthenticated git protocol on port 9418 is no longer supported.

  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.

ERROR: Command errored out with exit status 128: git clone -q git://github.com/Pycord-Development/pycord /tmp/pip-req-build-kd9qoj75 Check the logs for full command output.